#define QUAKEWORLD

#include "common/defs.qc"
#include "common/subs.qc"
#include "common/combat.qc"
#include "common/items.qc"
#include "common/weapons.qc"
#include "common/world.qc"
#include "common/client.qc"
#include "qw/spectate.qc"
#include "common/player.qc"
#include "common/doors.qc"
#include "common/buttons.qc"
#include "common/triggers.qc"
#include "common/plats.qc"
#include "common/misc.qc"

#include "qw/server.qc"

